topics:
- name: joy
  topic: joy_teleop/cmd_vel
  timeout: 0.5
  priority: 10
- name: key_teleop
  topic: key_teleop/cmd_vel
  timeout: 0.5
  priority: 5
- name: external
  topic: cmd_vel
  timeout: 0.5
  priority: 1

locks:
- name    : e_stop
  topic   : e_stop
  timeout : 0.0
  priority: 255